# Нагадування по Markdown

Надаємо невелике нагадування записів в
[Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb) (LaTeX):

Markdown | Preview
--- | ---
`**bold text**` | **bold text**
 \\$\frac{x}{y}\\$ | $\frac{x}{y}$
 \\$p^{x}_{y}\\$ | $p^{x}_{y}$
\\$x \cdot y\\$ | $x \cdot y$
\\$\sqrt{x}\\$ | $\sqrt{x}$
\\$\pi\\$ | $\pi$
\\$\approx\\$ | $\approx$

І ще декілька прикладів:

```markdown
$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

 $$
 I =
 \left (\begin{array}{cc}
 1 & 0\\
 0 & 1
 \end{array}\right)
 $$
```

$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

$I =
\left (\begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right)$
 ---

# Завдання 1.
В шаблоні наведені числові вектори $\overline{a}$ та $\overline{b}$. Порахуй наступне:
- сума $\overline{a}$ та $\overline{b}$
- різниця $\overline{a}$ та $\overline{b}$
- сума $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}^T$.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- добуток Адамара (Hadamard product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

In [1]:
res = np.add(a,b)
res

NameError: name 'np' is not defined

In [ ]:
res = np.subtract(a,b)
res

array([[0.5, 1. , 1. , 1. , 1. ]])

In [ ]:
# Пояснення: При додаванні вектор-стовпця до вектора-рядка кожен елемент вектора-стовпця додається до відповідного елемента вектора-рядка, створюючи новий вектор з новими результатами.

res = np.add(a,b.T)
res

array([[1.5, 2.5, 3.5, 4.5, 5.5],
       [2. , 3. , 4. , 5. , 6. ],
       [3. , 4. , 5. , 6. , 7. ],
       [4. , 5. , 6. , 7. , 8. ],
       [5. , 6. , 7. , 8. , 9. ]])

In [ ]:
res = np.dot(a, b.T)
res

array([[40.5]])

In [ ]:
# Пояснення: При множені кількість стовпчиків 1-матриці повинні = кількості рядків другої. В нас дві матриці 1х5, збігу немає - множення неможливо.
res = np.dot(a,b)
res

ValueError: shapes (1,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [ ]:
# Пояснення: Добуток Адамара поєлементне множення кожного відповідного елемента з двох матрицю Аа11 * Ba11, і так до кінця
res = np.multiply(a,b)
res

array([[ 0.5,  2. ,  6. , 12. , 20. ]])

In [ ]:
# Пояснення:Поэлемнтне ділення, не згідно арефметичних правил. Згідно арефметичних треба np.true_divide
res = np.divide(a,b)
res

array([[2.        , 2.        , 1.5       , 1.33333333, 1.25      ]])

In [ ]:
# Пояснення: Кожен елемент вектора-рядка ділится на відповідгий елемента вектора-стовпчика, створюючи новий вектор з новими результатами.

res = np.divide(a,b.T)
res

array([[ 2.        ,  4.        ,  6.        ,  8.        , 10.        ],
       [ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [ 0.5       ,  1.        ,  1.5       ,  2.        ,  2.5       ],
       [ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667],
       [ 0.25      ,  0.5       ,  0.75      ,  1.        ,  1.25      ]])

# Завдання 2
В цьому завданні ти навчишся перетворювати вектори за допомогою афінних перетворень.  
Дано вектор:
$$
x =
\left(\begin{array}{cc}
2\\
1
\end{array}\right)
$$


Виконай аналітично наступні завдання задавши матрицю перетворення та застосуй її до вектора $x$:

1. Зменши вектор $x$ в 2 рази по вісі $OX$ та збільш в 3 рази по вісі $OY$.
2. Відобрази вектор $x$ відносно початку координат.
3. Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.
4. Змісти вектор $x$ на 60° по вісі $OY$.
5. Поверни вектор $x$ на 30°.
6. Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

#### 2.1 Зменши вектор  $x$  в 2 рази по вісі  OX  та збільш в 3 рази по вісі  OY .

$$
M_1 =
\left (\begin{array}{cc}
0,5 & 0\\
0 & 3
\end{array}\right)
$$

$$
M_1x =
\left(\begin{array}{cc}
0,5 & 0\\
0 & 3
\end{array}\right)
\left (\begin{array}{cc}
2\\
1
\end{array}\right)=
\left(\begin{array}{cc}
0,5 \cdot 2 + 0 \cdot 1\\
0 \cdot 2 + 3 \cdot 1
\end{array}\right)=
\left(\begin{array}{cc}
1\\
3
\end{array}\right)
$$

In [ ]:
 import numpy as np
 x = np.array([[2],[1]])
 m = np.array([[0.5, 0], [0, 3]])
 new_vector = m.dot(x)
 new_vector

array([[1.],
       [3.]])

#### 2.2 Відобрази вектор $x$ відносно початку координат.

$$
M_2 = \left (\begin{array}{cc}
-1 & 0\\
 0 & -1
\end{array}\right)
$$
\\
$$
\\
M_2x = \left (\begin{array}{cc}
-2\\
 -1
\end{array}\right)
$$

In [ ]:
 x = np.array([[2],[1]])
 m = np.array([[-1, 0], [0, -1]])
 new_vector = m.dot(x)
 new_vector


array([[-2],
       [-1]])

#### 2.3 Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.

$$
M_3 = \left (\begin{array}{cc}
-3\\
 1
\end{array}\right)
$$
\\
$$
M_3x = \left (\begin{array}{cc}
-1\\
 2
\end{array}\right)
$$

In [ ]:
 x = np.array([[2],[1]])
 m = np.array([[-3],[1]])
 new_vector = x + m
 new_vector


array([[-1],
       [ 2]])

#### 2.4 Змісти вектор $x$ на 60° по вісі $OY$.


$$
M_4 = ?
\\
M_4x = ?
$$

In [ ]:
angle_radian = np.radians(60)
tan = np.tan(angle_radian)
x = np.array([[2],[1]])
m = np.array([[1,0],[-(tan), 1]])
new_vector = m.dot(x)
new_vector

array([[ 2.        ],
       [-2.46410162]])

#### 2.5 Поверни вектор $x$ на 30°.

$$
M_5 = \left (\begin{array}{cc}
cos30 (0.8) & -sin30(-0.5)(\\
sin30(0.5) & cos30(0.8)
\end{array}\right)
$$

$$
M_5x = \left (\begin{array}{cc}
1,2\\
1,8
\end{array}\right)
$$

In [2]:
angle_radian = np.radians(30)
cos = np.cos(angle_radian)
sin = np.sin(angle_radian)
x = np.array([[2],[1]])
m = np.array([[cos,-(sin)],[sin, cos]])
# new_vector = m.dot(x)

m


NameError: name 'np' is not defined

#### 2.6 Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

$$
M_6 = M_5 \cdot M_4 \cdot M_2 \cdot M_1 = ?
$$

$$
M_6 =
\left (\begin{array}{cc}
0.08 & -2.96\\
0.51 & -0.46
\end{array}\right)
\\
M_6x = \left (\begin{array}{cc}
-2,8\\
 0,5
\end{array}\right)
$$

In [ ]:
cos30 = np.cos(30)
sin30 = np.sin(30)
tan = np.tan(60)
x = np.array([[2],[1]])
m5 = np.array([[cos30,-(sin30)],[sin30, cos30]])
m4 = np.array([[1,0],[-(tan), 1]])
m2 = np.array([[-1, 0], [0, -1]])
m1 = np.array([[0.5, 0], [0, 3]])
m21 = m2.dot(m1)
m421 = m4.dot(m21)
m6 = m5.dot(m421)
m6x = m6.dot(x)
m6x

array([[-2.8021363 ],
       [ 0.57464397]])

# Завдання 2 (Альтернативне)

In [ ]:
import cv2 as cv
import urllib
import numpy as np
from google.colab.patches import cv2_imshow as cv_imshow

# Read an image
def read_image_by_url(url):
    req = urllib.request.urlopen(url)
    arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
    img = cv.imdecode(arr, -1)
    return img

url = ''

img = read_image_by_url(url)

In [ ]:
cv_imshow(img)